repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      # TODO: re-enable `golangci-lint` and fix all linter errors before re-committing
      # - id: golangci-lint
      - id: go-critic
      - id: go-build
      - id: go-mod-tidy
